### ISSUE TITLE
Invalid JWS

### ISSUE THREAD

**Issue by phileo** [googlesamples/android-play-safetynet#11]
in the `SafetyNetApi.AttestationResponse.getJWSResult()` jws string, it is supposed to contain 2 periods.  However, I only see one single period.

Any ideas as to why the JWS string does not contain 2 periods?

**Comment by VarunVats9** [comment]
For me it worked only after installing the apk on real device, instead of emulator. On emulator it was showing invalid JWS without any period.

**Comment by moulanaaidi** [comment]
hi, did you solve this issue? I'm facing the same issue IllegalArgumentException.

**Comment by KaisNeffati** [comment]
Hello there, Is there any news considering this issue ? Facing the same problem ! @orodrig-google 
Exception in thread "main" java.lang.IllegalArgumentException
       at com.google.api.client.repackaged.com.google.common.base.Preconditions
.checkArgument(Preconditions.java:111)
       at com.google.api.client.util.Preconditions.checkArgument(Preconditions.
java:37)
       at com.google.api.client.json.webtoken.JsonWebSignature$Parser.parse(Jso
nWebSignature.java:599)
       at OfflineVerify.parseAndVerify(OfflineVerify.java:40)
       at OfflineVerify.process(OfflineVerify.java:97)
       at OfflineVerify.main(OfflineVerify.java:124)
:runOfflineVerify FAILED

FAILURE: Build failed with an exception.

**Comment by KaisNeffati** [comment]
I've found out the problem! The problem results in the logger which only log 4024 characters The real value could not be parsed by the logger Debug and inspect the element to get the real value
