### ISSUE TITLE
gradlew  runOnlineVerify  -PsignedStatement=**   gradlew runOfflineVerify -PsignedStatement=***  报错

### ISSUE THREAD

**Issue by leiwuyue** [googlesamples/android-play-safetynet#16]
Failure: Network error while connecting to the Google Service https://www.googleapis.com/androidcheck/v1/attestations/verify?key=kkkk 

 Task :runOfflineVerify FAILED
xception in thread "main" java.lang.IllegalArgumentException
       at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:108)
       at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:37)
       at com.google.api.client.json.webtoken.JsonWebSignature$Parser.parse(JsonWebSignature.java:599)
       at OfflineVerify.parseAndVerify(OfflineVerify.java:40)
       at OfflineVerify.process(OfflineVerify.java:97)
       at OfflineVerify.main(OfflineVerify.java:124)

**Comment by huajianjiang** [comment]
国内被墙？
